@url = http://localhost:4000/api

##Aquí para autores

GET {{url}}/autores
Authorization: 
###
###
GET {{url}}/autores/3

###
POST {{url}}/autores
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJhZG1pbiIsImlhdCI6MTczMDIyNzg5NX0.7z8gHJLYmdN8x2OAfZ2buFZ0pu200wFzWF84TOeNR1w

{
  "nombre": "Arturo Gimni",
  "email": "gimi_ artu@gmail.com",
  "imagen": "https://images.unsplash.com/photo-1714941923094-8c75b86c2833?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
PUT {{url}}/autores/37
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJhZG1pbiIsImlhdCI6MTczMDIyNzg5NX0.7z8gHJLYmdN8x2OAfZ2buFZ0pu200wFzWF84TOeNR1w

{
  "nombre": "Arturo Gimni Adonis",
  "email": "gimi_ artu@gmail.com",
  "imagen": "https://images.unsplash.com/photo-1714941923094-8c75b86c2833?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
DELETE {{url}}/autores/37
# solo va a ocurrir si hemos creado el 18, arriba puesto

##Aquí para posts
###
GET {{url}}/posts
Authorization: 
###
###
GET {{url}}/posts/4

###
GET {{url}}/posts/autores-post/1

###
POST {{url}}/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJhZG1pbiIsImlhdCI6MTczMDIyNzg5NX0.7z8gHJLYmdN8x2OAfZ2buFZ0pu200wFzWF84TOeNR1w

  {
    "id": 52,
    "titulo": "Un futuro más sano y sostenible",
    "descripcion": "El ser humano construyendo un futuro sano, sostenible y que respeta el medioambiente",
    "fecha_creacion": "2024-10-28T10:08:14",
    "categoria": "Ciencia y Salud",
    "autor_id": 12
  }

###
PUT {{url}}/posts/51
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJhZG1pbiIsImlhdCI6MTczMDIyNzg5NX0.7z8gHJLYmdN8x2OAfZ2buFZ0pu200wFzWF84TOeNR1w

  {
    "id": 51,
    "titulo": "El Rol de los Animales en la Ciencia ",
    "descripcion": "Cómo los animales han contribuido a saber más sobre el ser humano",
    "fecha_creacion": "2024-10-28T10:08:14",
    "categoria": "Ciencia y Salud",
    "autor_id": 10
  }
###
DELETE {{url}}/posts/52
# solo va a ocurrir si hemos creado el 51, arriba puesto